name: slotformer
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - ipykernel
  - jupyter
  - numpy
  - pip
  - python=3.8
  - pytorch
  - pip:
    - einops
    - matplotlib
    - opencv-python
    - pillow
    - pytorch-lightning
    - scikit-image
    - torch
    - torchvision
    - tqdm
    - wandb
